### ISSUE TITLE
Doesn't kill all processes. 

### ISSUE THREAD

**Issue by K9Paradox** [Hypertext-Assassin-RSS/Adobe-Background-Process-Killer#1]
Multiple processes aren't killed by this. 
Adobe IPC Broker
CCLibraries
Notification Manager for Adobe Creative cloud
>RunTime Broker
> Adobe Notification Client
Node.js runtime adobe

**Comment by HypertextAssassinRajith** [comment]
Please  download latest version to solve this issue

**Comment by HypertextAssassinRajith** [comment]
https://github.com/Hypertext-Assassin-RSS/Adobe-Background-Process-Killer/releases/download/V2.0/Adobe.Killer.zip
